//! This module contains types which are used almost purely as inter-import-stage data
//! and which contain minimal functionality on their own, as opposed to more featureful
//! types in [`super::import_types`] which provide various lookup tables and other parsing,
//! or other types in [`super`] which are complicated algorithms or powerful 'overall
//! process'-related constructs.

use std::fmt::{Display, Formatter};
use std::ops::Deref;
use std::path::{Path, PathBuf};
use std::sync::Arc;

use crate::import::{BackgroundType, ImportType, OtherSkinType, SkinType};

// --- PRE-IMPORT STAGE ---

/// The raw data fed into the import process
pub struct QueuedFile {
  /// An externally defined import type. For most implementations, this is probably hardcoded as Automatic.
  pub kind: ImportType,
  pub path: PathBuf,
  pub binary: Arc<[u8]>
}

// SpecificImportType before Zip is handled by `explore_files`
#[derive(Debug, Hash, Eq, PartialEq, Copy, Clone, serde_with::SerializeDisplay)]
pub enum SpecificImportTypeWithZip {
  Zip,
  Other(SpecificImportType)
}
impl Display for SpecificImportTypeWithZip {
  fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
    match self {
      Self::Zip => write!(f, "zip"),
      Self::Other(other) => write!(f, "{other}")
    }
  }
}

// --- POST `explore_files` STAGE ---

/// File representation after the `explore_files` stage
#[derive(Clone)]
pub struct ProcessedQueuedFile {
  pub specific_kind: SpecificImportType,
  pub kind: ImportType,
  pub path: PathBuf,
  pub binary: Arc<[u8]>
}
/// A distilled copy of an import type that's been rendered to a more specific form than the public API.
#[derive(Debug, Hash, Eq, PartialEq, Copy, Clone, serde_with::SerializeDisplay)]
pub enum SpecificImportType {
  TPSE,
  Skin(SkinType),
  OtherSkin(OtherSkinType),
  SoundEffects,
  Background(BackgroundType),
  Music
}
impl Display for SpecificImportType {
  fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
    match self {
      SpecificImportType::TPSE => write!(f, "tpse"),
      SpecificImportType::Skin(subtype) => write!(f, "{} skin", subtype),
      SpecificImportType::OtherSkin(subtype) => write!(f, "{} skin", subtype),
      SpecificImportType::SoundEffects => write!(f, "sound effects"),
      SpecificImportType::Background(subtype) => write!(f, "{} background", subtype),
      SpecificImportType::Music => write!(f, "music")
    }
  }
}

/// A broad category of content based on a file extension
pub enum FileType {
  Zip,
  TPSE,
  Image,
  Video,
  Audio
}
impl FileType {
  pub fn from_mime(_string: &str) -> Option<FileType> {
    todo!()
  }
  pub fn from_extension(filename: &Path) -> Option<FileType> {
    let ext = Path::new(&filename).extension()?.to_str()?;
    match ext {
      "zip" => Some(FileType::Zip),
      "tpse" => Some(FileType::TPSE),
      "svg" | "png" | "jpg" | "jpeg" | "gif" | "webp" => Some(FileType::Image),
      "mp4" | "webm" => Some(FileType::Video),
      "ogg" | "mp3" | "flac" => Some(FileType::Audio),
      _ => return None
    }
  }
}

// --- POST `reduce_types` STAGE ---

/// A collated form of a SpecificImportType suitable for performing the actual import step.
/// Generated by the `reduce_types` stage
#[derive(Debug)]
pub enum ImportTask {
  AnimatedSkinFrames(SkinType, Vec<AnimatedSkinFrame>),
  SoundEffects(Vec<SoundEffect>),
  Basic {
    import_type: SpecificImportType,
    path: PathBuf,
    binary: Buffer
  }
}
#[derive(Debug)]
pub struct AnimatedSkinFrame {
  pub path: PathBuf,
  pub binary: Buffer
}
#[derive(Debug)]
pub struct SoundEffect {
  /// The name of the sound effect, usually the file name sans extension
  pub name: String,
  pub path: PathBuf,
  pub binary: Buffer
}

pub struct Buffer(Arc<[u8]>);
impl std::fmt::Debug for Buffer {
  fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
    write!(f, "<{} bytes>", self.0.len())
  }
}
impl From<Arc<[u8]>> for Buffer {
  fn from(value: Arc<[u8]>) -> Self {
    Self(value)
  }
}
impl Into<Arc<[u8]>> for Buffer {
  fn into(self) -> Arc<[u8]> {
    self.0
  }
}
impl Deref for Buffer {
  type Target = Arc<[u8]>;
  fn deref(&self) -> &Self::Target {
    &self.0
  }
}