//! This module contains types which are used almost purely as inter-import-stage data
//! and which contain minimal functionality on their own, as opposed to more featureful
//! types in [`super::import_types`] which provide various lookup tables and other parsing,
//! or other types in [`super`] which are complicated algorithms or powerful 'overall
//! process'-related constructs.

use std::fmt::{Debug, Formatter};
use std::path::PathBuf;
use std::sync::Arc;

use crate::import::{SkinType, TypeStage3, TypeStage4};
use crate::util::Buffer;

/// A container of a file and its determined type at various stages of import.
/// This type is commonly parameterized with [ImportType](crate::import::ImportType) when
/// being created externally to pass to `import()`, and between various import stages gains
/// types of [TypeStage1](crate::import::TypeStage1) through [TypeStage4].
/// See [ImportType](crate::import::ImportType) for more detail on the stages.
#[derive(Clone)]
pub struct ImportFile<Stage> {
  pub import_type: Stage,
  pub path: PathBuf,
  pub binary: Arc<[u8]>
}
impl<S> Debug for ImportFile<S> where S: Debug {
  fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
    f.debug_struct("ImportFile")
      .field("import_type", &self.import_type)
      .field("path", &self.path)
      .field("binary", &format_args!("<{} bytes>", self.binary.len()))
      .finish()
  }
}


// --- POST `partition_import_groups` STAGE ---

/// A DecisionTree represents one _decision to be made_. Making that decision
/// adds a number of files to the import process and may expose further decisions.
#[derive(Debug)]
pub struct DecisionTree {
  pub id: u64,
  pub description: String,
  pub required: bool,
  pub options: Vec<DecisionTreeOption>,
}
impl DecisionTree {
  pub fn visit(&self, acceptor: &mut impl FnMut(&Self)) {
    acceptor(&self);
    for option in &self.options {
      for subtree in &option.subtrees {
        subtree.visit(acceptor);
      }
    }
  }
}
/// A DecisionTreeOption is one possible choice that can be made when deciding a DecisionTree's choice
#[derive(Debug)]
pub struct DecisionTreeOption {
  pub description: String,
  pub files: Vec<ImportFile<TypeStage3>>,
  pub subtrees: Vec<DecisionTree>
}

// --- POST `reduce_types` STAGE ---

/// A collated form of a SpecificImportType suitable for performing the actual import step.
/// Generated by the `reduce_types` stage
#[derive(Debug)]
pub enum ImportTask {
  AnimatedSkinFrames(SkinType, Vec<AnimatedSkinFrame>),
  SoundEffects(Vec<SoundEffect>),
  Basic {
    import_type: TypeStage4,
    path: PathBuf,
    binary: Buffer
  }
}
#[derive(Debug)]
pub struct AnimatedSkinFrame {
  pub path: PathBuf,
  pub binary: Buffer
}
#[derive(Debug)]
pub struct SoundEffect {
  /// The name of the sound effect, usually the file name after removing extension and filekey
  pub name: String,
  pub path: PathBuf,
  pub binary: Buffer
}
