#[derive(Debug, Hash, Eq, PartialEq, Copy, Clone, serde::Serialize, serde::Deserialize)]
#[serde(tag = "subtype", rename_all = "snake_case")]
pub enum OtherSkinType {
  Board,
  Queue,
  Grid,
  ParticleBeam,
  ParticleBeamsBeam,
  ParticleBigBox,
  ParticleBox,
  ParticleChip,
  ParticleChirp,
  ParticleDust,
  ParticleFBox,
  ParticleFire,
  ParticleParticle,
  ParticleSmoke,
  ParticleStar,
  ParticleFlake,
  RankD,
  RankDPlus,
  RankCMinus,
  RankC,
  RankCPlus,
  RankBMinus,
  RankB,
  RankBPlus,
  RankAMinus,
  RankA,
  RankAPlus,
  RankSMinus,
  RankS,
  RankSPlus,
  RankSS,
  RankU,
  RankX,
  RankZ
}